name: Packer

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'config/packer/**'
      - 'projects/**'



jobs:
  build-packer:
    if: github.repository == '502y/Minecraft-Mod-Language-Package'
    name: Build / Cache Packer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: src

      # 缓存程序。一方面，在不同job之间需要这么做；另一方面，大约可以改善运行时间？
      # actions/cache的逻辑会在job末尾缓存打包程序；如果不命中，就自行构造程序。
      - name: Cache Packer
        id: cache-packer
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-Packer-${{ hashFiles('src/Packer/**') }}
          path: |
            Packer.exe
            git2-*.dll
          lookup-only: true

      # 构造程序
      - name: Build Packer if not cached
        if: steps.cache-packer.outputs.cache-hit != 'true'
        run: dotnet publish .\src\Packer\Packer.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

  # build-uploader:
  #   if: github.repository == '502y/Minecraft-Mod-Language-Package'
  #   name: Build / Cache Uploader
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1
  #         sparse-checkout: src

  #     # 缓存程序。一方面，在不同job之间需要这么做；另一方面，大约可以改善运行时间？
  #     # actions/cache的逻辑会在job末尾缓存打包程序；如果不命中，就自行构造程序。
  #     - name: Cache Uploader
  #       id: cache-uploader
  #       uses: actions/cache@v4
  #       with:
  #         key: ${{ runner.os }}-Uploader-${{ hashFiles('src/Uploader/**') }}
  #         path: Uploader.exe
  #         lookup-only: true

  #     # 构造程序
  #     - name: Build Uploader if not cached
  #       if: steps.cache-uploader.outputs.cache-hit != 'true'
  #       run: dotnet publish .\src\Uploader\Uploader.csproj -o ./ -r win-x64 -p:PublishSingeFile=true

  initialize-release:
    if: github.repository == '502y/Minecraft-Mod-Language-Package'
    name: Initialize Release
    runs-on: windows-latest
    steps:

      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=Snapshot-$(date '+%Y%m%d%H%M%s')" >> $GITHUB_OUTPUT
        shell: bash

        # Create the release: https://github.com/actions/create-release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Snapshot-${{ steps.create_timestamp.outputs.timestamp }}
          release_name: 汉化资源包-Snapshot-${{ steps.create_timestamp.outputs.timestamp }}
          draft: false
          prerelease: false
    outputs:
      tag-name: ${{ steps.create_timestamp.outputs.timestamp }}


  pack:
    if: github.repository == '502y/Minecraft-Mod-Language-Package'
    name: Pack Resources and Upload Artifacts/Releases
    needs: [ build-packer, initialize-release ] # 显然，需要存在打包程序，才能打包。
    strategy:
      fail-fast: false # 把正常的文件先打包了，避免一处错误阻塞整个仓库。
      matrix:
        # 版本列表。将对这里的每个版本判断，按需打包。
        # 如需添加新版本，在这里添加即可。
        version: [ "1.12.2", "1.16", "1.16-fabric", "1.18", "1.18-fabric", "1.19", "1.20", "1.20-fabric", "1.21", "1.21-fabric" ]
    runs-on: windows-latest
    outputs:
      # 为每个版本创建独立的输出变量
      updated_versions_1_12_2: ${{ steps.collect-updated.outputs.version_1_12_2 }}
      updated_versions_1_16: ${{ steps.collect-updated.outputs.version_1_16 }}
      updated_versions_1_16_fabric: ${{ steps.collect-updated.outputs.version_1_16_fabric }}
      updated_versions_1_18: ${{ steps.collect-updated.outputs.version_1_18 }}
      updated_versions_1_18_fabric: ${{ steps.collect-updated.outputs.version_1_18_fabric }}
      updated_versions_1_19: ${{ steps.collect-updated.outputs.version_1_19 }}
      updated_versions_1_20: ${{ steps.collect-updated.outputs.version_1_20 }}
      updated_versions_1_20_fabric: ${{ steps.collect-updated.outputs.version_1_20_fabric }}
      updated_versions_1_21: ${{ steps.collect-updated.outputs.version_1_21 }}
      updated_versions_1_21_fabric: ${{ steps.collect-updated.outputs.version_1_21_fabric }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20 # 显然，需要有提交历史才能比较提交。20这个数是任意的。

      # 由于Github的限制，这里需要重新拉取打包程序。
      - name: Restore Packer
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-Packer-${{ hashFiles('source/Packer/**') }}
          path: |
            Packer.exe
            git2-*.dll
          fail-on-cache-miss: true # 前一步理应构造过的。如果不命中，肯定有问题，不如直接挂掉。

      - name: Check changed path on ${{ matrix.version }}
        uses: MarceloPrado/has-changed-path@v1.0
        id: check-changes
        with:
          # 判断位置：该版本文件、该版本配置、代码
          paths: > 
            projects/${{ matrix.version }}
            config/packer/${{ matrix.version }}.json
            src/**

      - name: Run Packer for ${{ matrix.version }}
        # 分发包中应当包含全部内容
        run: ./Packer --version="${{ matrix.version }}"
        # 运行逻辑：内容有更改 或 手动运行
        if: steps.check-changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'

      # Artifact 上传内容：每个版本一个压缩包，包含了资源包和md5校验文件
      - name: Upload Artifact for ${{ matrix.version }}
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-Mod-Language-Package-${{ matrix.version }}
          path: |
            Minecraft-Mod-Language-Package-${{ matrix.version }}.zip
            ${{ matrix.version }}.md5
        if: steps.check-changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'

      # Upload release asset: https://github.com/actions/upload-release-asset
      - name: Update release asset for ${{ matrix.version }}
        id: upload-release-asset
        if: steps.check-changes.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.initialize-release.outputs.upload-url }}
          asset_path: Minecraft-Mod-Language-Package-${{ matrix.version }}.zip
          asset_name: Minecraft-Mod-Language-Package-${{ matrix.version }}.zip
          asset_content_type: application/zip

      - name: Collect updated versions
        id: collect-updated
        run: |
          if [ "${{ steps.check-changes.outputs.changed }}" == "true" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # 根据当前矩阵版本设置对应的输出变量
            case "${{ matrix.version }}" in
              "1.12.2")
                echo "version_1_12_2=1.12.2" >> $GITHUB_OUTPUT
                ;;
              "1.16")
                echo "version_1_16=1.16" >> $GITHUB_OUTPUT
                ;;
              "1.16-fabric")
                echo "version_1_16_fabric=1.16-fabric" >> $GITHUB_OUTPUT
                ;;
              "1.18")
                echo "version_1_18=1.18" >> $GITHUB_OUTPUT
                ;;
              "1.18-fabric")
                echo "version_1_18_fabric=1.18-fabric" >> $GITHUB_OUTPUT
                ;;
              "1.19")
                echo "version_1_19=1.19" >> $GITHUB_OUTPUT
                ;;
              "1.20")
                echo "version_1_20=1.20" >> $GITHUB_OUTPUT
                ;;
              "1.20-fabric")
                echo "version_1_20_fabric=1.20-fabric" >> $GITHUB_OUTPUT
                ;;
              "1.21")
                echo "version_1_21=1.21" >> $GITHUB_OUTPUT
                ;;
              "1.21-fabric")
                echo "version_1_21_fabric=1.21-fabric" >> $GITHUB_OUTPUT
                ;;
            esac
          fi
        shell: bash
        continue-on-error: true

  update-index:
    if: github.repository == '502y/Minecraft-Mod-Language-Package'
    name: Update Version Index (Optional)
    needs: [pack, initialize-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download existing index.json if exists
        run: |
          if [ -f version-index.json ]; then
            cp version-index.json version-index.json.bak
          else
            echo "{}" > version-index.json
          fi

      - name: Update index.json
        env:
          RELEASE_TAG: ${{ needs.initialize-release.outputs.release-tag }}
          # 获取所有版本的更新状态，即使某些版本未触发也不会影响
          UPDATED_VERSIONS_1_12_2: ${{ needs.pack.outputs.updated_versions_1_12_2 }}
          UPDATED_VERSIONS_1_16: ${{ needs.pack.outputs.updated_versions_1_16 }}
          UPDATED_VERSIONS_1_16_FABRIC: ${{ needs.pack.outputs.updated_versions_1_16_fabric }}
          UPDATED_VERSIONS_1_18: ${{ needs.pack.outputs.updated_versions_1_18 }}
          UPDATED_VERSIONS_1_18_FABRIC: ${{ needs.pack.outputs.updated_versions_1_18_fabric }}
          UPDATED_VERSIONS_1_19: ${{ needs.pack.outputs.updated_versions_1_19 }}
          UPDATED_VERSIONS_1_20: ${{ needs.pack.outputs.updated_versions_1_20 }}
          UPDATED_VERSIONS_1_20_FABRIC: ${{ needs.pack.outputs.updated_versions_1_20_fabric }}
          UPDATED_VERSIONS_1_21: ${{ needs.pack.outputs.updated_versions_1_21 }}
          UPDATED_VERSIONS_1_21_FABRIC: ${{ needs.pack.outputs.updated_versions_1_21_fabric }}
        run: |
          python3 - <<EOF
          import json
          import os
      
          index_file = "version-index.json"
          try:
            with open(index_file, "r") as f:
              index = json.load(f)
          except FileNotFoundError:
            index = {}
              
          # 收集所有版本的更新状态
          updated_versions = []
          version_vars = [
            "UPDATED_VERSIONS_1_12_2",
            "UPDATED_VERSIONS_1_16", 
            "UPDATED_VERSIONS_1_16_FABRIC",
            "UPDATED_VERSIONS_1_18",
            "UPDATED_VERSIONS_1_18_FABRIC",
            "UPDATED_VERSIONS_1_19",
            "UPDATED_VERSIONS_1_20",
            "UPDATED_VERSIONS_1_20_FABRIC",
            "UPDATED_VERSIONS_1_21",
            "UPDATED_VERSIONS_1_21_FABRIC"
          ]
          
          # 只有实际更新的版本才会被添加到列表中
          for var in version_vars:
              version = os.environ.get(var, "")
              if version:
                  updated_versions.append(version)
          
          release_tag = os.environ.get("RELEASE_TAG", "")

          # 为所有更新的版本更新索引
          for v in updated_versions:
            if v:
              index[v] = release_tag
    
          with open(index_file, "w") as f:
            json.dump(index, f, indent=2)
          EOF

      - name: Commit and Push index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version-index.json
          git commit -m "Update version index for $RELEASE_TAG" || echo "No changes to commit"
          git push

  upload:
    if: github.repository == 'CFPAOrg/Minecraft-Mod-Language-Package'
    name: Upload Resource Packs to Remote Server
    needs: [ pack ] # 显然，需要打包完成，并且存在上传程序，才可以上传给分发服务器
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: src

      # 构造程序
      - name: Build Uploader
        run: dotnet publish .\src\Uploader\Uploader.csproj -o ./ -r win-x64 -p:PublishSingeFile=true

      # 还原artifact（资源包）
      - name: Restore Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      # feat: UTC 20:00~21:00 取消上传（避开远程服务器的4:00-4:10）
      - name: Fail at inappropriate time
        run: if [ `date -u +%H` -eq 20 ]; then exit -1; fi
        shell: bash

      - name: Run Uploader
        run: .\Uploader --host="${{ secrets.SSH_IP }}" --name="${{ secrets.SSH_USER }}" --password="${{ secrets.SSH_PWD }}"
