name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 支持手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ Workflow is running!"

      - name: Check GitHub Token
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "❌ GITHUB_TOKEN is missing!"
            exit 1
          else
            echo "✅ GITHUB_TOKEN is available!"
          fi

      - name: Show repo info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
